[project]
name = "dap391m"
version = "0.1.0"
description = "DAP391m playground."
readme = "README.md"
authors = [
    { name = "ForeverWeLearn", email = "theanh11052006@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "altair>=6.3.0",
    "bokeh>=3.9.2",
    "bokeh-sampledata>=2025.0",
    "hvplot>=0.12.2",
    "ipykernel>=7.3.0",
    "lmstudio>=1.5.0",
    "pandas>=3.0.5",
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
]

[project.scripts]
lab3 = "dap391m.lab3.app:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
