[project]
name = "dap391m"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ForeverWeLearn", email = "theanh11052006@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "kagglehub[pandas-datasets]>=1.0.2",
    "pandas>=3.0.5",
    "polars>=1.44.2",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
dap391m = "dap391m:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
